# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=5000)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='blog/media', verbose_name='My Photo')),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
